# Generated by Django 5.0.1 on 2024-02-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_ordermodel_email_ordermodel_name_ordermodel_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
